- name: NTP
  apt: pkg=ntp
- apt: pkg=vlan,iproute
- name: Useful stuff
  apt: pkg=tree,dstat,less,vim,bash-completion
- apt: pkg=screen
- copy: src=config/screenrc dest=/etc/screenrc
# Requires ansible 1.6
#- alternatives: name=editor path=/usr/bin/vim.basic
